### ISSUE TITLE
1.0 Compatibility 

### ISSUE THREAD

**Issue by alecloudenback** [JuliaIO/FLAC.jl#19]
````
(v1.0) pkg> add FLAC
  Updating registry at `C:\Users\user\.julia\registries\General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package FLAC [05003743]:
 FLAC [05003743] log:
 ├─possible versions are: [0.1.0, 0.2.0, 0.2.2] or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions [0.1.0, 0.2.0, 0.2.2]
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left
````

**Comment by SimonDanisch** [comment]
@dmbates, did you use Clang for this? And if yes, do you still have the script?

**Comment by dmbates** [comment]
@SimonDanisch To tell you the truth, I don't remember if I used Clang which also means that I don't have the script.

Would it be best for me to transfer ownership to some other individual or group?  I don't really use this package any more.

**Comment by SimonDanisch** [comment]
You could transfer it to JuliaIO ;)

**Comment by dmbates** [comment]
I am happy to do that but I will need permission to create a repository on JuliaIO.  I am not currently a member.

**Comment by SimonDanisch** [comment]
I invited you to be a member!

**Comment by dmbates** [comment]
Thanks,  The repository has been transferred.

**Comment by staticfloat** [comment]
We are now compatible with Julia 1.3+
